#%RAML 1.0
title: field-validation

/customer:
  post:
    body:
      application/json:
        properties:
          person:
            type: object
            properties:
              name:
                type: string
                required: true
                minLength: 5
              mobile:
                type: string
                required: true
                minLength: 10
                